#!/usr/bin/env python

# Build
# python setup.py bdist_wheel -- requires wheel to be installed
# Test Install
# python -m pip install dist/project-version-py3-none-any.whl
# Upload
# python -m twine upload dist/project-version-py3-none-any.whl

from extractor import extract

if __name__ == "__main__":
    extract()